const defaultTheme = require("tailwindcss/defaultTheme");
module.exports = {
  sans: [
    "Work Sans",
    "system-ui",
    "BlinkMacSystemFont",
    "-apple-system",
    "Segoe UI",
    "Roboto",
    "Oxygen",
    "Ubuntu",
    "Cantarell",
    "Fira Sans",
    "Droid Sans",
    "Helvetica Neue",
    "sans-serif",
  ],
  serif: [
    "Lora",
    "Lucida Bright",
    "Lucidabright",
    "Lucida Serif",
    "Lucida",
    "DejaVu Serif",
    "Bitstream Vera Serif",
    "Liberation Serif",
    "Georgia",
    "serif",
  ],
  brand: [
    "JeanLuc",
    "system-ui",
    "BlinkMacSystemFont",
    "-apple-system",
    "Segoe UI",
    "Roboto",
    "Oxygen",
    "Ubuntu",
    "Cantarell",
    "Fira Sans",
    "Droid Sans",
    "Helvetica Neue",
    "sans-serif",
  ],
}