[build]
  command = "npx astro build --site $URL"
[build.environment]
  NODE_VERSION = "16.16.0"
[functions]
  directory = "functions"
  external_node_modules = ["svgo", "@11ty/eleventy-fetch"]
[context]

[context.production]
[context.production.environment]
  GOES = "here"

[context.deploy-preview]
  command = "npx astro build --site $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npx astro build --site $DEPLOY_URL"
[context.branch-deploy.environment]
  GOES = "here"

[dev]
  command = "npm run start"
  functions = "functions"
  publish = "public"
  port = 8888
  targetPort = 3000
  framework = "#custom"
